In [67]:
import pyodbc
import time
import numpy as pd
import pandas as pd
from datetime import date, time
import requests
import json
from pandas.io.json import json_normalize

In [68]:
url = 'https://services1.arcgis.com/CY1LXxl9zlJeBuRZ/arcgis/rest/services/Florida_COVID19_Case_Line_Data_2021/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json'

In [74]:
r = requests.get(url)
r.json()

rigin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NO',
    'Case1': 1610514000000,
    'EventDate': 1609718400000,
    'ChartDate': 1610514000000,
    'ObjectId': 952}},
  {'attributes': {'County': 'Escambia',
    'Age': '89',
    'Age_group': '85+ years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'UNKNOWN',
    'Hospitaliz': 'UNKNOWN',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'UNKNOWN',
    'Case1': 1612242000000,
    'EventDate': 1612224000000,
    'ChartDate': 1612242000000,
    'ObjectId': 953}},
  {'attributes': {'County': 'Duval',
    'Age': '20',
    'Age_group': '15-24 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': 'UNKNOWN',
    'Hospitaliz': 'UNKNOWN',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NA',
    'Case1': 1612587600000,
    'EventDate': 1612569600000,
    'ChartDate': 1612587600000,
    'ObjectId': 954}},
  {'attributes': {'County': 'Leon',
    'Age': '25',
    'Age_group': '25-34 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': 'UNKNOWN',
    'Hospitaliz': 'UNKNOWN',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'YES',
    'Case1': 1612242000000,
    'EventDate': 1612224000000,
    'ChartDate': 1612242000000,
    'ObjectId': 955}},
  {'attributes': {'County': 'Manatee',
    'Age': '47',
    'Age_group': '45-54 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1612587600000,
    'EventDate': 1612569600000,
    'ChartDate': 1612587600000,
    'ObjectId': 956}},
  {'attributes': {'County': 'Dade',
    'Age': '65',
    'Age_group': '65-74 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'YES',
    'Case1': 1612242000000,
    'EventDate': 1612224000000,
    'ChartDate': 1612242000000,
    'ObjectId': 957}},
  {'attributes': {'County': 'Manatee',
    'Age': '42',
    'Age_group': '35-44 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NO',
    'Case1': 1612587600000,
    'EventDate': 1612396800000,
    'ChartDate': 1612587600000,
    'ObjectId': 958}},
  {'attributes': {'County': 'Alachua',
    'Age': '61',
    'Age_group': '55-64 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'YES',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NO',
    'Case1': 1612674000000,
    'EventDate': 1612569600000,
    'ChartDate': 1612674000000,
    'ObjectId': 959}},
  {'attributes': {'County': 'Hernando',
    'Age': '1',
    'Age_group': '0-4 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'UNKNOWN',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'UNKNOWN',
    'Case1': 1612587600000,
    'EventDate': 1612650250000,
    'ChartDate': 1612587600000,
    'ObjectId': 960}},
  {'attributes': {'County': 'Polk',
    'Age': '70',
    'Age_group': '65-74 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'YES',
    'Hospitaliz': 'YES',
    'Died': 'Yes',
    'Case_': 'Yes',
    'Contact': 'UNKNOWN',
    'Case1': 1612674000000,
    'EventDate': 1612656000000,
    'ChartDate': 1612674000000,
    'ObjectId': 961}},
  {'attributes': {'County': 'Dade',
    'Age': '45',
    'Age_group': '45-54 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1612414800000,
    'EventDate': 1612483200000,
    'ChartDate': 1612414800000,
    'ObjectId': 962}},
  {'attributes': {'County': 'Manatee',
    'Age': '31',
    'Age_group': '25-34 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NO',
    'Case1': 1612587600000,
    'EventDate': 1612569600000,
    'ChartDate': 1612587600000,
    'ObjectId': 963}},
  {'attributes': {'County': 'Walton',
    'Age': '44',
    'Age_group': '35-44 years',
    'Gender': 'Unknown',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'UNKNOWN',
    'Case1': 1612674000000,
    'EventDate': 1612483200000,
    'ChartDate': 1612674000000,
    'ObjectId': 964}},
  {'attributes': {'County': 'Dade',
    'Age': '14',
    'Age_group': '5-14 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1612501200000,
    'EventDate': 1611100800000,
    'ChartDate': 1612501200000,
    'ObjectId': 965}},
  {'attributes': {'County': 'Manatee',
    'Age': '9',
    'Age_group': '5-14 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1612587600000,
    'EventDate': 1612569600000,
    'ChartDate': 1612587600000,
    'ObjectId': 966}},
  {'attributes': {'County': 'Bay',
    'Age': '57',
    'Age_group': '55-64 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1612674000000,
    'EventDate': 1612483200000,
    'ChartDate': 1612674000000,
    'ObjectId': 967}},
  {'attributes': {'County': 'Dade',
    'Age': '33',
    'Age_group': '25-34 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NO',
    'Case1': 1612501200000,
    'EventDate': 1611532800000,
    'ChartDate': 1612501200000,
    'ObjectId': 968}},
  {'attributes': {'County': 'Manatee',
    'Age': '7',
    'Age_group': '5-14 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1612587600000,
    'EventDate': 1612310400000,
    'ChartDate': 1612587600000,
    'ObjectId': 969}},
  {'attributes': {'County': 'Lee',
    'Age': '46',
    'Age_group': '45-54 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': 'UNKNOWN',
    'Hospitaliz': 'UNKNOWN',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1611291600000,
    'EventDate': 1611273600000,
    'ChartDate': 1611291600000,
    'ObjectId': 970}},
  {'attributes': {'County': 'Dade',
    'Age': '17',
    'Age_group': '15-24 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NO',
    'Case1': 1612501200000,
    'EventDate': 1612483200000,
    'ChartDate': 1612501200000,
    'ObjectId': 971}},
  {'attributes': {'County': 'Manatee',
    'Age': '13',
    'Age_group': '5-14 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1612587600000,
    'EventDate': 1612569600000,
    'ChartDate': 1612587600000,
    'ObjectId': 972}},
  {'attributes': {'County': 'Lee',
    'Age': '51',
    'Age_group': '45-54 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': 'UNKNOWN',
    'Hospitaliz': 'UNKNOWN',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NA',
    'Case1': 1611291600000,
    'EventDate': 1611273600000,
    'ChartDate': 1611291600000,
    'ObjectId': 973}},
  {'attributes': {'County': 'Dade',
    'Age': '37',
    'Age_group': '35-44 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NO',
    'Case1': 1612501200000,
    'EventDate': 1612483200000,
    'ChartDate': 1612501200000,
    'ObjectId': 974}},
  {'attributes': {'County': 'Broward',
    'Age': '28',
    'Age_group': '25-34 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NO',
    'Case1': 1612587600000,
    'EventDate': 1612569600000,
    'ChartDate': 1612587600000,
    'ObjectId': 975}},
  {'attributes': {'County': 'Lee',
    'Age': '27',
    'Age_group': '25-34 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': 'UNKNOWN',
    'Hospitaliz': 'UNKNOWN',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NA',
    'Case1': 1611291600000,
    'EventDate': 1611273600000,
    'ChartDate': 1611291600000,
    'ObjectId': 976}},
  {'attributes': {'County': 'Broward',
    'Age': '51',
    'Age_group': '45-54 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1612501200000,
    'EventDate': 1611619200000,
    'ChartDate': 1612501200000,
    'ObjectId': 977}},
  {'attributes': {'County': 'Broward',
    'Age': '22',
    'Age_group': '15-24 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': 'UNKNOWN',
    'Hospitaliz': 'UNKNOWN',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'UNKNOWN',
    'Case1': 1612587600000,
    'EventDate': 1612569600000,
    'ChartDate': 1612587600000,
    'ObjectId': 978}},
  {'attributes': {'County': 'Escambia',
    'Age': '79',
    'Age_group': '75-84 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'YES',
    'Case1': 1611291600000,
    'EventDate': 1611014400000,
    'ChartDate': 1611291600000,
    'ObjectId': 979}},
  {'attributes': {'County': 'Orange',
    'Age': '51',
    'Age_group': '45-54 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1612501200000,
    'EventDate': 1611964800000,
    'ChartDate': 1612501200000,
    'ObjectId': 980}},
  {'attributes': {'County': 'Dade',
    'Age': '47',
    'Age_group': '45-54 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'UNKNOWN',
    'Hospitaliz': 'UNKNOWN',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'UNKNOWN',
    'Case1': 1612587600000,
    'EventDate': 1612569600000,
    'ChartDate': 1612587600000,
    'ObjectId': 981}},
  {'attributes': {'County': 'Hillsborough',
    'Age': '17',
    'Age_group': '15-24 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': None,
    'Hospitaliz': 'UNKNOWN',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1613710800000,
    'EventDate': 1613769217000,
    'ChartDate': 1613710800000,
    'ObjectId': 982}},
  {'attributes': {'County': 'Escambia',
    'Age': '25',
    'Age_group': '25-34 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': 'UNKNOWN',
    'Hospitaliz': 'UNKNOWN',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'UNKNOWN',
    'Case1': 1612501200000,
    'EventDate': 1612483200000,
    'ChartDate': 1612501200000,
    'ObjectId': 983}},
  {'attributes': {'County': 'Broward',
    'Age': '64',
    'Age_group': '55-64 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': 'UNKNOWN',
    'Hospitaliz': 'UNKNOWN',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'UNKNOWN',
    'Case1': 1612587600000,
    'EventDate': 1612569600000,
    'ChartDate': 1612587600000,
    'ObjectId': 984}},
  {'attributes': {'County': 'Dade',
    'Age': '40',
    'Age_group': '35-44 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': 'UNKNOWN',
    'Hospitaliz': 'UNKNOWN',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NA',
    'Case1': 1612501200000,
    'EventDate': 1612483200000,
    'ChartDate': 1612501200000,
    'ObjectId': 985}},
  {'attributes': {'County': 'Orange',
    'Age': '25',
    'Age_group': '25-34 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1612501200000,
    'EventDate': 1612137600000,
    'ChartDate': 1612501200000,
    'ObjectId': 986}},
  {'attributes': {'County': 'Broward',
    'Age': '50',
    'Age_group': '45-54 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1612587600000,
    'EventDate': 1612483200000,
    'ChartDate': 1612587600000,
    'ObjectId': 987}},
  {'attributes': {'County': 'Duval',
    'Age': '50',
    'Age_group': '45-54 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': 'UNKNOWN',
    'Hospitaliz': 'UNKNOWN',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NA',
    'Case1': 1612501200000,
    'EventDate': 1612483200000,
    'ChartDate': 1612501200000,
    'ObjectId': 988}},
  {'attributes': {'County': 'Orange',
    'Age': '0',
    'Age_group': '0-4 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1612501200000,
    'EventDate': 1612137600000,
    'ChartDate': 1612501200000,
    'ObjectId': 989}},
  {'attributes': {'County': 'Orange',
    'Age': '15',
    'Age_group': '15-24 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'YES',
    'Case1': 1612501200000,
    'EventDate': 1612310400000,
    'ChartDate': 1612501200000,
    'ObjectId': 990}},
  {'attributes': {'County': 'Broward',
    'Age': '23',
    'Age_group': '15-24 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NO',
    'Case1': 1612587600000,
    'EventDate': 1612224000000,
    'ChartDate': 1612587600000,
    'ObjectId': 991}},
  {'attributes': {'County': 'Clay',
    'Age': '0',
    'Age_group': '0-4 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1612501200000,
    'EventDate': 1612483200000,
    'ChartDate': 1612501200000,
    'ObjectId': 992}},
  {'attributes': {'County': 'Dade',
    'Age': '59',
    'Age_group': '55-64 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'YES',
    'Case1': 1612501200000,
    'EventDate': 1612310400000,
    'ChartDate': 1612501200000,
    'ObjectId': 993}},
  {'attributes': {'County': 'Broward',
    'Age': '50',
    'Age_group': '45-54 years',
    'Gender': 'Female',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NO',
    'Case1': 1612587600000,
    'EventDate': 1612569600000,
    'ChartDate': 1612587600000,
    'ObjectId': 994}},
  {'attributes': {'County': 'Flagler',
    'Age': '61',
    'Age_group': '55-64 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'UNKNOWN',
    'Case1': 1612587600000,
    'EventDate': 1612051200000,
    'ChartDate': 1612587600000,
    'ObjectId': 995}},
  {'attributes': {'County': 'Leon',
    'Age': '38',
    'Age_group': '35-44 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NO',
    'Case1': 1612501200000,
    'EventDate': 1612137600000,
    'ChartDate': 1612501200000,
    'ObjectId': 996}},
  {'attributes': {'County': 'Broward',
    'Age': '37',
    'Age_group': '35-44 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'YES',
    'Case1': 1612587600000,
    'EventDate': 1612310400000,
    'ChartDate': 1612587600000,
    'ObjectId': 997}},
  {'attributes': {'County': 'Seminole',
    'Age': '24',
    'Age_group': '15-24 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'Unknown',
    'Origin': 'NA',
    'EDvisit': 'UNKNOWN',
    'Hospitaliz': 'UNKNOWN',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'NA',
    'Case1': 1612587600000,
    'EventDate': 1612569600000,
    'ChartDate': 1612587600000,
    'ObjectId': 998}},
  {'attributes': {'County': 'Polk',
    'Age': '15',
    'Age_group': '15-24 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1612501200000,
    'EventDate': 1612310400000,
    'ChartDate': 1612501200000,
    'ObjectId': 999}},
  {'attributes': {'County': 'Broward',
    'Age': '76',
    'Age_group': '75-84 years',
    'Gender': 'Male',
    'Jurisdicti': 'FL resident',
    'Travel_rel': 'No',
    'Origin': 'NA',
    'EDvisit': 'NO',
    'Hospitaliz': 'NO',
    'Died': 'NA',
    'Case_': 'Yes',
    'Contact': 'Yes',
    'Case1': 1612587600000,
    'EventDate': 1612137600000,
    'ChartDate': 1612587600000,
    'ObjectId': 1000}},
  ...]}

In [71]:
r.json().keys()

dict_keys(['objectIdFieldName', 'uniqueIdField', 'globalIdFieldName', 'fields', 'exceededTransferLimit', 'features'])

In [78]:
features = r.json()['features']
df = json_normalize(features)
df['attributes.Cases'] = 1
df.head()

,attributes.Age,attributes.Age_group,attributes.Case1,attributes.Case_,attributes.ChartDate,attributes.Contact,attributes.County,attributes.Died,attributes.EDvisit,attributes.EventDate,attributes.Gender,attributes.Hospitaliz,attributes.Jurisdicti,attributes.ObjectId,attributes.Origin,attributes.Travel_rel,attributes.Cases
0,41,35-44 years,1612242000000,Yes,1612242000000,NO,Dade,NA,UNKNOWN,1612224000000,Male,UNKNOWN,FL resident,1,NA,Unknown,1
1,48,45-54 years,1612242000000,Yes,1612242000000,NO,Palm Beach,NA,NO,1612224000000,Male,NO,FL resident,2,NA,No,1
2,21,15-24 years,1612242000000,Yes,1612242000000,Yes,Collier,NA,NO,1611964800000,Male,NO,FL resident,3,NA,No,1
3,54,45-54 years,1612242000000,Yes,1612242000000,YES,Orange,NA,UNKNOWN,1611705600000,Female,UNKNOWN,FL resident,4,NA,Unknown,1
4,51,45-54 years,1612242000000,Yes,1612242000000,NO,Marion,NA,UNKNOWN,1610755200000,Female,UNKNOWN,FL resident,5,NA,Unknown,1